package main

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"rsc.io/script"
	"rsc.io/script/scripttest"
)

func Test(t *testing.T) {
	e := script.NewEngine()
	e.Quiet = true
	e.Cmds = scripttest.DefaultCmds()
	e.Cmds["check-templates"] = checkTemplatesCommand()
	ctx := t.Context()
	scripttest.Test(t, ctx, e, nil, filepath.FromSlash("testdata/*.txt"))
}

// fixtureSpec is the schema for testdata/fixtures/<name>/fixture.json.
type fixtureSpec struct {
	Flags        []string `json:"flags"`
	WantExitCode int      `json:"wantExitCode"`
	// WantStderr lists substrings that must each appear in stderr output.
	// Use forward slashes; they are normalised to the OS path separator.
	WantStderr []string `json:"wantStderr"`
}

// TestFixtures runs check-templates against real Go + template files under
// testdata/fixtures/<name>/ and verifies exit code and stderr output.
func TestFixtures(t *testing.T) {
	fixturesDir := filepath.Join("testdata", "fixtures")
	entries, err := os.ReadDir(fixturesDir)
	if err != nil {
		t.Fatalf("reading fixtures dir: %v", err)
	}

	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		name := entry.Name()
		dir := filepath.Join(fixturesDir, name)

		t.Run(name, func(t *testing.T) {
			specPath := filepath.Join(dir, "fixture.json")
			data, err := os.ReadFile(specPath)
			if err != nil {
				t.Fatalf("reading fixture.json: %v", err)
			}
			var spec fixtureSpec
			if err := json.Unmarshal(data, &spec); err != nil {
				t.Fatalf("parsing fixture.json: %v", err)
			}

			absDir, err := filepath.Abs(dir)
			if err != nil {
				t.Fatalf("abs path: %v", err)
			}

			var stdout, stderr bytes.Buffer
			args := append(spec.Flags, "./...")
			gotCode := run(absDir, args, &stdout, &stderr)

			if gotCode != spec.WantExitCode {
				t.Errorf("exit code: got %d, want %d\nstderr:\n%s", gotCode, spec.WantExitCode, stderr.String())
			}

			stderrStr := filepath.ToSlash(stderr.String())
			for _, want := range spec.WantStderr {
				if !strings.Contains(stderrStr, want) {
					t.Errorf("stderr missing %q\nfull stderr:\n%s", want, stderrStr)
				}
			}
		})
	}
}

// TestTSExtract runs check-templates -o ts-extract against real Go + template
// files and verifies the generated .ts output contains expected substrings.
func TestTSExtract(t *testing.T) {
	extractDir := filepath.Join("testdata", "ts-extract")
	entries, err := os.ReadDir(extractDir)
	if err != nil {
		t.Fatalf("reading ts-extract dir: %v", err)
	}

	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		name := entry.Name()
		dir := filepath.Join(extractDir, name)

		t.Run(name, func(t *testing.T) {
			absDir, err := filepath.Abs(dir)
			if err != nil {
				t.Fatalf("abs path: %v", err)
			}

			outDir := t.TempDir()
			var stdout, stderr bytes.Buffer
			args := []string{"-o", "ts-extract", "-ts-outdir", outDir, "./..."}
			gotCode := run(absDir, args, &stdout, &stderr)

			if gotCode != 0 {
				t.Fatalf("exit code: got %d, want 0\nstderr:\n%s", gotCode, stderr.String())
			}

			// Read all generated .ts files and check for basic validity.
			tsFiles, err := filepath.Glob(filepath.Join(outDir, "*.ts"))
			if err != nil {
				t.Fatal(err)
			}
			if len(tsFiles) == 0 {
				t.Fatal("no .ts files generated")
			}

			for _, tsFile := range tsFiles {
				content, err := os.ReadFile(tsFile)
				if err != nil {
					t.Fatal(err)
				}
				tsContent := string(content)

				// Should have the header comment.
				if !strings.Contains(tsContent, "auto-generated by check-templates") {
					t.Error("missing header comment")
				}
				// Should not contain raw template actions.
				if strings.Contains(tsContent, "{{") {
					t.Errorf("generated .ts still contains template actions:\n%s", tsContent)
				}
				// Should contain typed placeholders.
				if !strings.Contains(tsContent, "undefined!") {
					t.Errorf("generated .ts missing typed placeholders:\n%s", tsContent)
				}

				t.Logf("Generated %s:\n%s", filepath.Base(tsFile), tsContent)
			}
		})
	}
}

// TestTSCheck runs check-templates -o ts-check against real Go + template
// files and verifies that TypeScript diagnostics are surfaced and mapped
// back to the template source.
func TestTSCheck(t *testing.T) {
	checkDir := filepath.Join("testdata", "ts-check")
	entries, err := os.ReadDir(checkDir)
	if err != nil {
		t.Fatalf("reading ts-check dir: %v", err)
	}

	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		name := entry.Name()
		dir := filepath.Join(checkDir, name)

		t.Run(name, func(t *testing.T) {
			absDir, err := filepath.Abs(dir)
			if err != nil {
				t.Fatalf("abs path: %v", err)
			}

			// Read the fixture spec if present.
			specPath := filepath.Join(dir, "fixture.json")
			var spec fixtureSpec
			if data, err := os.ReadFile(specPath); err == nil {
				if err := json.Unmarshal(data, &spec); err != nil {
					t.Fatalf("parsing fixture.json: %v", err)
				}
			} else {
				// Default: expect exit code 1 (diagnostics found).
				spec.WantExitCode = 1
			}

			var stdout, stderr bytes.Buffer
			args := append([]string{"-o", "ts-check"}, spec.Flags...)
			args = append(args, "./...")
			gotCode := run(absDir, args, &stdout, &stderr)

			stderrStr := filepath.ToSlash(stderr.String())
			t.Logf("stderr:\n%s", stderrStr)

			if gotCode != spec.WantExitCode {
				t.Errorf("exit code: got %d, want %d\nstderr:\n%s", gotCode, spec.WantExitCode, stderrStr)
			}

			for _, want := range spec.WantStderr {
				if !strings.Contains(stderrStr, want) {
					t.Errorf("stderr missing %q\nfull stderr:\n%s", want, stderrStr)
				}
			}
		})
	}
}

func checkTemplatesCommand() script.Cmd {
	return script.Command(script.CmdUsage{
		Summary: "check-templates [dir]",
		Args:    "[dir]",
	}, func(state *script.State, args ...string) (script.WaitFunc, error) {
		return func(state *script.State) (string, string, error) {
			var stdout, stderr bytes.Buffer
			code := run(state.Getwd(), args, &stdout, &stderr)
			var err error
			if code != 0 {
				err = script.ErrUsage
			}
			return stdout.String(), stderr.String(), err
		}, nil
	})
}
